import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'motion/react';
import { Lock, Activity, AlertTriangle } from 'lucide-react';
export function IntroScreen({ onStart }) {
    return (_jsxs("div", { className: "min-h-screen bg-gradient-to-b from-slate-950 via-purple-950/80 to-slate-900 flex flex-col items-center justify-center p-4 overflow-hidden relative", children: [_jsx("div", { className: "absolute inset-0 overflow-hidden pointer-events-none", children: _jsx("div", { className: "absolute bottom-0 left-0 right-0 h-[60%] opacity-20", style: {
                        background: 'linear-gradient(to top, transparent, rgba(139, 92, 246, 0.1))',
                        transform: 'perspective(800px) rotateX(60deg)',
                        transformOrigin: 'bottom',
                    }, children: _jsx("div", { className: "w-full h-full", style: {
                            backgroundImage: `
                linear-gradient(rgba(139, 92, 246, 0.4) 2px, transparent 2px),
                linear-gradient(90deg, rgba(139, 92, 246, 0.4) 2px, transparent 2px)
              `,
                            backgroundSize: '80px 80px',
                        } }) }) }), _jsx("div", { className: "absolute left-4 top-1/4 bottom-1/4 w-32 opacity-30 pointer-events-none hidden lg:block", children: _jsx("div", { className: "w-full h-full bg-gradient-to-r from-purple-900/50 to-transparent border-l-2 border-cyan-500/30 p-3", children: [...Array(8)].map((_, i) => (_jsx("div", { className: "mb-2 h-8 bg-cyan-900/20 border border-cyan-500/30 rounded" }, i))) }) }), _jsx("div", { className: "absolute right-4 top-1/4 bottom-1/4 w-32 opacity-30 pointer-events-none hidden lg:block", children: _jsx("div", { className: "w-full h-full bg-gradient-to-l from-purple-900/50 to-transparent border-r-2 border-cyan-500/30 p-3", children: [...Array(8)].map((_, i) => (_jsx("div", { className: "mb-2 h-8 bg-cyan-900/20 border border-cyan-500/30 rounded" }, i))) }) }), _jsx("div", { className: "absolute top-10 left-10 w-2 h-64 bg-gradient-to-b from-purple-500 to-transparent opacity-40 blur-sm" }), _jsx("div", { className: "absolute top-10 right-10 w-2 h-64 bg-gradient-to-b from-purple-500 to-transparent opacity-40 blur-sm" }), _jsx("div", { className: "absolute bottom-20 left-20 w-2 h-48 bg-gradient-to-t from-cyan-400 to-transparent opacity-40 blur-sm" }), _jsx("div", { className: "absolute bottom-20 right-20 w-2 h-48 bg-gradient-to-t from-cyan-400 to-transparent opacity-40 blur-sm" }), [...Array(15)].map((_, i) => (_jsx(motion.div, { className: "absolute w-1 h-1 bg-cyan-400 rounded-full", initial: {
                    x: Math.random() * window.innerWidth,
                    y: Math.random() * window.innerHeight,
                    opacity: 0
                }, animate: {
                    opacity: [0, 1, 0],
                    y: [null, Math.random() * window.innerHeight]
                }, transition: {
                    duration: 3 + Math.random() * 3,
                    repeat: Infinity,
                    delay: Math.random() * 2
                } }, i))), _jsxs(motion.div, { initial: { opacity: 0, y: -30 }, animate: { opacity: 1, y: 0 }, transition: { duration: 1 }, className: "text-center z-10 max-w-6xl w-full", children: [_jsxs("div", { className: "relative mb-8", children: [_jsx("div", { className: "absolute top-0 left-0 w-16 h-16 border-t-2 border-l-2 border-cyan-400/50" }), _jsx("div", { className: "absolute top-0 right-0 w-16 h-16 border-t-2 border-r-2 border-cyan-400/50" }), _jsx(motion.div, { initial: { opacity: 0, y: -20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.3 }, className: "text-sm text-cyan-400 font-mono mb-2", children: "Escuadr\u00F3n Sable P\u00FAppra \u2013 Acceso restringido / Nivel Omega" }), _jsx(motion.h1, { initial: { opacity: 0, scale: 0.9 }, animate: { opacity: 1, scale: 1 }, transition: { delay: 0.5, duration: 0.8 }, className: "text-4xl md:text-6xl lg:text-7xl mb-2 text-white tracking-wider", style: {
                                    textShadow: '0 0 20px rgba(168, 85, 247, 0.8), 0 0 40px rgba(168, 85, 247, 0.4)'
                                }, children: "ENIGMA ROOM:" }), _jsx(motion.h2, { initial: { opacity: 0, scale: 0.9 }, animate: { opacity: 1, scale: 1 }, transition: { delay: 0.7, duration: 0.8 }, className: "text-3xl md:text-5xl lg:text-6xl text-white tracking-widest", style: {
                                    textShadow: '0 0 20px rgba(168, 85, 247, 0.8), 0 0 40px rgba(168, 85, 247, 0.4)'
                                }, children: "PROTOCOLO HALCYON-9" })] }), _jsx(motion.div, { initial: { opacity: 0, scale: 0.8 }, animate: { opacity: 1, scale: 1 }, transition: { delay: 1, duration: 1 }, className: "relative mb-12 mx-auto max-w-2xl", children: _jsxs("div", { className: "relative h-80 flex items-center justify-center", children: [_jsx(motion.div, { animate: { rotate: 360 }, transition: { duration: 20, repeat: Infinity, ease: 'linear' }, className: "absolute bottom-0 w-80 h-12 rounded-full border-2 border-cyan-400/30", style: {
                                        background: 'radial-gradient(ellipse at center, rgba(34, 211, 238, 0.2) 0%, transparent 70%)',
                                        boxShadow: '0 0 40px rgba(34, 211, 238, 0.3), inset 0 0 20px rgba(34, 211, 238, 0.2)'
                                    } }), _jsxs(motion.div, { animate: {
                                        rotateY: 360,
                                        y: [0, -10, 0]
                                    }, transition: {
                                        rotateY: { duration: 20, repeat: Infinity, ease: 'linear' },
                                        y: { duration: 4, repeat: Infinity, ease: 'easeInOut' }
                                    }, className: "relative", style: { transformStyle: 'preserve-3d' }, children: [_jsxs("div", { className: "relative w-32 h-40", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-b from-cyan-400/40 to-cyan-600/40 rounded-lg", style: {
                                                        boxShadow: '0 0 40px rgba(34, 211, 238, 0.6), inset 0 0 20px rgba(34, 211, 238, 0.3)',
                                                        border: '2px solid rgba(34, 211, 238, 0.5)'
                                                    } }), [...Array(6)].map((_, i) => (_jsx("div", { className: "absolute left-0 right-0 h-1 bg-cyan-300/50", style: { top: `${20 + i * 12}%` } }, i)))] }), [0, 90, 180, 270].map((rotation, i) => (_jsx("div", { className: "absolute top-1/2 left-1/2 w-32 h-4", style: {
                                                transform: `translate(-50%, -50%) rotateZ(${rotation}deg) translateX(60px)`,
                                                transformOrigin: 'left center'
                                            }, children: _jsx("div", { className: "w-full h-full bg-gradient-to-r from-cyan-500/60 to-transparent rounded", style: {
                                                    boxShadow: '0 0 20px rgba(34, 211, 238, 0.6)'
                                                } }) }, i)))] }), _jsx(motion.div, { initial: { opacity: 0, x: -50 }, animate: { opacity: 1, x: 0 }, transition: { delay: 1.5 }, className: "absolute left-0 top-20 bg-red-900/80 border border-red-500 px-3 py-1 rounded text-xs font-mono", children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(AlertTriangle, { className: "w-3 h-3 text-red-400" }), _jsx("span", { className: "text-red-200", children: "FIREWALL QU-37" })] }) }), _jsx(motion.div, { initial: { opacity: 0, x: 50 }, animate: { opacity: 1, x: 0 }, transition: { delay: 1.7 }, className: "absolute right-0 top-32 bg-red-900/80 border border-red-500 px-3 py-1 rounded text-xs font-mono", children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Lock, { className: "w-3 h-3 text-red-400" }), _jsx("span", { className: "text-red-200", children: "LOCKDOWN" })] }) }), _jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 1.9 }, className: "absolute left-8 bottom-24 bg-cyan-900/80 border border-cyan-400 px-3 py-1 rounded text-xs font-mono", children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Activity, { className: "w-3 h-3 text-cyan-400" }), _jsx("span", { className: "text-cyan-200", children: "STATION 9-H" })] }) }), _jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 2.1 }, className: "absolute top-8 left-1/2 -translate-x-1/2 text-red-400 text-xs font-mono", children: "\u26A0 FIREWALL QU-37 DETECTED \u26A0" }), _jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 2.3 }, className: "absolute bottom-4 left-1/2 -translate-x-1/2 text-red-400 text-xs font-mono", children: "IMPACTO EN: 18:41" })] }) }), _jsx(motion.div, { initial: { opacity: 0, scale: 0.8 }, animate: { opacity: 1, scale: 1 }, transition: { delay: 2.5 }, className: "mb-8", children: _jsxs("button", { onClick: onStart, className: "relative group", children: [_jsx("div", { className: "absolute inset-0 rounded-full bg-gradient-to-r from-cyan-500/20 to-purple-500/20 blur-xl \n                          group-hover:blur-2xl transition-all" }), _jsxs("div", { className: "relative", children: [_jsx(motion.div, { animate: { rotate: 360 }, transition: { duration: 8, repeat: Infinity, ease: 'linear' }, className: "absolute inset-0 rounded-full", style: {
                                                padding: '4px',
                                                background: 'linear-gradient(45deg, #06b6d4, #a855f7, #06b6d4)',
                                                WebkitMask: 'linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)',
                                                WebkitMaskComposite: 'xor',
                                                maskComposite: 'exclude',
                                            } }), _jsxs("div", { className: "relative bg-slate-950/90 backdrop-blur-sm rounded-full p-8 border-2 border-cyan-400/50\n                            group-hover:border-cyan-400 transition-all duration-300\n                            shadow-[0_0_30px_rgba(6,182,212,0.3)] group-hover:shadow-[0_0_50px_rgba(6,182,212,0.6)]", children: [_jsx("div", { className: "text-2xl md:text-3xl font-mono text-cyan-400 tracking-widest", children: "INFILTRARSE" }), _jsx(motion.div, { animate: { scale: [1, 1.1, 1] }, transition: { duration: 2, repeat: Infinity }, className: "absolute inset-0 rounded-full border-2 border-cyan-400/30" })] })] })] }) }), _jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 2.7 }, className: "flex justify-center gap-3 md:gap-4", children: [...Array(5)].map((_, i) => (_jsxs(motion.div, { initial: { opacity: 0, scale: 0 }, animate: { opacity: 1, scale: 1 }, transition: { delay: 2.8 + i * 0.1 }, className: "w-16 h-16 md:w-20 md:h-20 rounded-lg border-2 border-cyan-500/30 bg-cyan-900/10\n                       flex items-center justify-center relative overflow-hidden group", children: [_jsx(Lock, { className: "w-6 h-6 md:w-8 md:h-8 text-cyan-700/50 group-hover:text-cyan-600/70 transition-colors" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-cyan-500/5 to-transparent" }), _jsx("div", { className: "absolute bottom-0 left-0 right-0 h-0.5 bg-cyan-500/20" })] }, i))) }), _jsx("div", { className: "absolute bottom-0 left-0 w-16 h-16 border-b-2 border-l-2 border-cyan-400/50" }), _jsx("div", { className: "absolute bottom-0 right-0 w-16 h-16 border-b-2 border-r-2 border-cyan-400/50" })] })] }));
}
